import type { ScryfallCard } from '@/lib/scryfall/types/scryfall';
import type { MpcCard, MpcSource } from './types';

const ALL_FORMATS = [
	'standard',
	'future',
	'historic',
	'gladiator',
	'pioneer',
	'explorer',
	'modern',
	'legacy',
	'pauper',
	'vintage',
	'penny',
	'commander',
	'oathbreaker',
	'brawl',
	'historicbrawl',
	'alchemy',
	'paupercommander',
	'duel',
	'oldschool',
	'premodern',
	'predh',
] as const;

const NOT_LEGAL_ALL = Object.fromEntries(
	ALL_FORMATS.map((f) => [f, 'not_legal'])
) as ScryfallCard['legalities'];

export function toSyntheticScryfallCard(card: MpcCard, source: MpcSource): ScryfallCard {
	const syntheticId = `mpc:${card.id}`;
	return {
		id: syntheticId,
		oracle_id: card.oracleId ?? syntheticId,
		object: 'card',
		name: card.name,
		lang: 'en',
		released_at: '2000-01-01',
		uri: '',
		scryfall_uri: '',
		layout: 'normal',
		image_uris: {
			small: card.imageUrl,
			normal: card.imageUrl,
			large: card.imageUrl,
			png: card.imageUrl,
			art_crop: card.imageUrl,
			border_crop: card.imageUrl,
		},
		image_status: 'highres_scan',
		highres_image: true,
		mana_cost: '',
		cmc: 0,
		type_line: '',
		colors: [],
		color_identity: [],
		keywords: [],
		legalities: NOT_LEGAL_ALL,
		games: [],
		reserved: false,
		foil: false,
		nonfoil: true,
		finishes: ['nonfoil'],
		oversized: false,
		promo: false,
		reprint: false,
		variation: false,
		set_id: 'mpc',
		set: 'mpc',
		set_name: source.name,
		set_type: 'memorabilia',
		set_uri: '',
		set_search_uri: '',
		scryfall_set_uri: '',
		rulings_uri: '',
		prints_search_uri: '',
		collector_number: card.id,
		digital: false,
		rarity: 'special',
		border_color: 'black',
		frame: '2015',
		full_art: false,
		textless: false,
		booster: false,
		story_spotlight: false,
		prices: {},
		related_uris: {},
	};
}
