// src/lib/mpc/mpc-tags.ts

// All canonical tag names and aliases from mpc_fil_format.txt, lowercased.
// A variant matching any of these is a styling tag, not a Scryfall card name.
const MPC_TAG_STRINGS = [
	// Art
	'art',
	'altered art',
	'altered',
	'filtered',
	'pixel art',
	'pixelated',
	'pixelized',
	'pop-out art',
	'popout art',
	'pop-out',
	'popout',
	'sketch art',
	'sketchified',
	'custom art',
	'alt art',
	'alternate',
	'alt',
	'alternate art',
	'ai art',
	'ai',
	'midjourney',
	'genai',
	'ai remaster',
	'artist art',
	'third party art',
	'3rd party art',
	'switched art',
	'upscaled scan',
	'upscaled',
	'upscaled art',
	'scryfall scan',
	'upscaled scryfall scan',
	// Frame
	'frame',
	'borderless',
	'borderless art',
	'borderless frame',
	'post-2023 borderless',
	'borderless 2023',
	'borderless alt',
	'custom-made frame',
	'custom frame',
	'ai frame',
	'minimalist',
	'minimalist frame',
	'min',
	'stonecutter',
	'stonecutter frame',
	'extended-art',
	'extended',
	'extended art',
	'extended frame',
	'extended art frame',
	'fnm promo',
	'fnm promo frame',
	'fnm frame',
	'universal promo frame',
	'universal promo',
	'wpn promo frame',
	'wpn promo',
	'foil-etched',
	'foil-etched frame',
	'etched frame',
	'etched',
	'full text',
	'full text frame',
	'futureshifted',
	'futureshifted frame',
	'fut frame',
	'future sight frame',
	'future shifted frame',
	'future shifted',
	'm15',
	'm15 frame',
	'regular frame',
	'modern',
	'modern frame',
	'eighth edition frame',
	'8th edition frame',
	'eighth edition',
	'8th edition',
	'8ed',
	'planeshifted',
	'planeshifted frame',
	'colorshifted frame',
	'planar chaos frame',
	'plc frame',
	'retro',
	'retro frame',
	'ancient frame',
	'ancient',
	'original frame',
	'og frame',
	'alpha',
	'beta',
	'unlimited',
	'abu',
	'classic',
	'showcase',
	'showcase frame',
	'extension showcase frame',
	'extension frame',
	'amonkhet invocations',
	'akh invocations',
	'capenna art deco',
	'snc art deco frame',
	'capenna art deco frame',
	'new capenna art deco',
	'new capenna art deco frame',
	'capenna golden age',
	'snc golden age frame',
	'capenna golden age frame',
	'new capenna golden age',
	'new capenna golden age frame',
	'capenna skyscraper',
	'snc skyscraper frame',
	'capenna skyscraper frame',
	'new capenna skyscraper',
	'new capenna skyscraper frame',
	'classicshifted',
	'classicshifted frame',
	'commander legends',
	'commander legends frame',
	'cmr frame',
	'd&d module',
	'd&d module frame',
	'd&d sourcebook',
	'd&d sourcebook frame',
	'doctor who tardis',
	'doctor who tardis frame',
	'who frame',
	'doctor who',
	'tardis',
	'tardis frame',
	'dominaria stained glass',
	'dmu frame',
	'stained glass frame',
	'dominaria stained glass frame',
	'stained glass',
	'eldraine enchanting tales',
	'wot frame',
	'enchanting tales frame',
	'enchanting tales',
	'eldraine enchanting tales frame',
	'eldraine storybook',
	'eld frame',
	'woe frame',
	'eldraine frame',
	'wilds of eldraine frame',
	'storybook frame',
	'eldraine storybook frame',
	'english mystical archive',
	'en sta frame',
	'fca showcase',
	'fca showcase frame',
	'fca frame',
	'final fantasy frame',
	'borderless source material',
	'source material',
	'ikoria crystal',
	'ikoria crystal frame',
	'crystal frame',
	'innistrad equinox',
	'mid frame',
	'innistrad equinox frame',
	'equinox frame',
	'midnight hunt frame',
	'innistrad fang',
	'vow frame',
	'fang frame',
	'crimson vow frame',
	'innistrad fang frame',
	'ixalan coin',
	'ixalan coin frame',
	'coin frame',
	'japanese mystical archive',
	'jp sta frame',
	'japan showcase',
	'japan showcase frame',
	'jp showcase',
	'jp showcase frame',
	'kaladesh inventions',
	'kld inventions',
	'kaldheim viking',
	'khm frame',
	'viking frame',
	'kaldheim frame',
	'kaldheim viking frame',
	'kamigawa neon',
	'neo neon frame',
	'kamigawa neon frame',
	'neon dynasty neon frame',
	'neon frame',
	'kamigawa ninja',
	'neo ninja frame',
	'kamigawa ninja frame',
	'neon dynasty ninja frame',
	'ninja frame',
	'kamigawa samurai',
	'neo samurai frame',
	'kamigawa samurai frame',
	'neon dynasty samurai frame',
	'samurai frame',
	'lotr ring',
	'ltr frame',
	'lotr ring frame',
	'ring frame',
	'lotr scrolls of middle-earth',
	'lotr scrolls of middle-earth frame',
	'scrolls of middle-earth frame',
	'scrolls of middle-earth',
	'm21 spellbook',
	'm21 frame',
	'signature spellbook frame',
	'signature spellbook',
	'm21 spellbook frame',
	'phyrexia oil',
	'one oil frame',
	'phyrexia oil frame',
	'oil frame',
	'phyrexian oil',
	'phyrexian oil frame',
	'ravnica architecture',
	'ravnica architecture frame',
	'architecture frame',
	'sketch frame',
	'mh2 frame',
	'sketch',
	'tarkir dragon wing',
	'tarkir dragon wing frame',
	'dragon wing frame',
	'theros nyx',
	'thb frame',
	'nyx frame',
	'theros beyond death frame',
	'theros nyx frame',
	'zendikar expeditions',
	'bfz expeditions',
	'exp frame',
	'zendikar hedron',
	'znr frame',
	'hedron frame',
	'zendikar rising frame',
	'zendikar hedron frame',
	'zendikar rising expeditions',
	'znr expeditions',
	'zne frame',
	'universes beyond',
	'ub frame',
	'universes beyond frame',
	'ub',
	'full-art',
	'full art',
	'full-art frame',
	'full art frame',
	'fullart frame',
	'fullart',
	// Misc
	'alternate name',
	'nickname',
	'godzilla nickname',
	'godzilla',
	'eternal night card',
	'black & white card',
	'realistic',
	'realistic wotc card',
	'realistic card',
	'secret lair',
	'secret lair card',
	'sld',
	'sld card',
	'textless',
	'textless card',
	'non-black border',
	'non-black',
	'special border',
	'unusual border',
	'gold border',
	'commemorative border',
	'collectors edition border',
	'world championship deck border',
	'world championship border',
	'wc border',
	'30th anniversary edition border',
	'30th anniversary border',
	'30a border',
	'silver border',
	'unset border',
	'white border',
	'unlimited border',
	'nsfw',
	'nsfw art',
	'not safe for work',
	'not safe for work art',
	'nudity',
	'nudity art',
	'gore',
	'gore art',
	// Universe
	'universe',
	'anime',
	'hatsune miku',
	'miku',
	'avatar the last airbender',
	'avatar',
	'tla',
	'tle',
	'dr who',
	'who',
	'fallout',
	'pip',
	'final fantasy',
	'fin',
	'ff',
	'in-multiverse',
	'mip',
	'uw',
	'universes within',
	'magic ip',
	'om1',
	'through the omenpaths',
	'league of legends',
	'lord of the rings',
	'ltr',
	'lotr',
	'my little pony',
	'mlp',
	'ponies the galloping',
	'spider-man',
	'spm',
	'spe',
	'warhammer 40k',
	'40k',
	'warhammer',
	// Common freeform variants that are never card names
	'normal',
	'v2',
	'v3',
	'v4',
	'pinlines',
	'foil',
];

export const MPC_TAGS: Set<string> = new Set(MPC_TAG_STRINGS);

export function isMpcTag(value: string): boolean {
	return MPC_TAGS.has(value.toLowerCase());
}
