export const MTG_LANGUAGES = [
	'English',
	'French',
	'German',
	'Spanish',
	'Italian',
	'Portuguese',
	'Japanese',
	'Korean',
	'Russian',
	'Simplified Chinese',
	'Traditional Chinese',
	'Hebrew',
	'Latin',
	'Ancient Greek',
	'Arabic',
	'Sanskrit',
	'Phyrexian',
] as const;

export type MtgLanguage = (typeof MTG_LANGUAGES)[number];

export const SCRYFALL_CODE_TO_LANGUAGE: Record<string, MtgLanguage> = {
	en: 'English',
	fr: 'French',
	de: 'German',
	es: 'Spanish',
	it: 'Italian',
	pt: 'Portuguese',
	ja: 'Japanese',
	ko: 'Korean',
	ru: 'Russian',
	zhs: 'Simplified Chinese',
	zht: 'Traditional Chinese',
	he: 'Hebrew',
	la: 'Latin',
	grc: 'Ancient Greek',
	ar: 'Arabic',
	sa: 'Sanskrit',
	ph: 'Phyrexian',
};

export const LANGUAGE_TO_SCRYFALL_CODE: Partial<Record<MtgLanguage, string>> = {
	English: 'en',
	French: 'fr',
	German: 'de',
	Spanish: 'es',
	Italian: 'it',
	Portuguese: 'pt',
	Japanese: 'ja',
	Korean: 'ko',
	Russian: 'ru',
	'Simplified Chinese': 'zhs',
	'Traditional Chinese': 'zht',
};
